/// Flutter icons Lodge_me
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Lodge_me
///      fonts:
///       - asset: fonts/Lodge_me.ttf
///
///
///
import 'package:flutter/widgets.dart';

// ignore: camel_case_types
class Lodge_me {
  Lodge_me._();

  static const _kFontFam = 'Lodge_me';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData lodge_me =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
